# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# South Facing Slope.py
# Created on: 2023-07-24 01:07:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: South Facing Slope <DEM> <South_Facing_Slope> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
DEM = arcpy.GetParameterAsText(0)
if DEM == '#' or not DEM:
    DEM = "C:\\Users\\OceeDITT\\Documents\\Geospatial Analysis\\SIWES\\TopoNsk MAP\\raster" # provide a default value if unspecified

South_Facing_Slope = arcpy.GetParameterAsText(1)
if South_Facing_Slope == '#' or not South_Facing_Slope:
    South_Facing_Slope = "c:\\users\\oceeditt\\documents\\arcgis\\default.gdb\\rastercalc" # provide a default value if unspecified

# Local variables:
Aspect_raster = "C:\\Users\\OceeDITT\\Documents\\ArcGIS\\Default.gdb\\Aspect_raste1"

# Process: Aspect
arcpy.gp.Aspect_sa(DEM, Aspect_raster, "PLANAR", "METER")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(\"%Aspect raster%\" > 135) & (\"%Aspect raster%\" < 225)", South_Facing_Slope)

